name: deploy my lamda function

on:
  push: 
    branches: 
        - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out the code
       uses: actions/checkout@v2
     - name: set up Python
       uses: actions/setup-python@v2
       with: 
         python-version: 3.8
     - name: Install librairies
       run: |
            cd function
            python -m pip install --upgrade pip
            if [-f requirements.txt ]; then pip install -r requirements.txt -t .;fi
     - name: Create Zip bundle
       run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
     - name: Archive thie artefact
       uses: actions/upload-artifact@v2
       with:
         name: zipped-bundle
         path: ${{ github.sha }}.zip
       
  publish:
    runs-on: ubuntu-latest
    steps: 
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.run.number }}
          release_name: Release from ${{ github.run.number }}
          body: New release for ${{ github.sh  }}. Release notes on the documentation site
          draft: false
          prerelease: false
 
        
